AllCops:
  NewCops: enable
  TargetRubyVersion: 2.3

Layout/ClosingHeredocIndentation:
  Enabled: false

Layout/HeredocIndentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Naming/FileName:
  Enabled: false

Style/CaseEquality:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Lambda:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
